import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PocketBlog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='w-full min-h-[80vh] items-center flex-col flex-wrap'>
          <Header />
          {children}
        </main>
        <div id='modal'></div>
      </body>
    </html>
  );
}
